### ISSUE TITLE
Investigate if `python_pip` workflow requires a virtualenv

### ISSUE THREAD

**Issue by sanathkr** [awslabs/aws-lambda-builders#13]
**Description:**
There is a `TODO` in the code that talks about trying to discover a virtualenv where the packager can run. Is this a real requirement? Can we just live with a Python and PIP executable available in the shell? 

If this is a real requirement, what are some strategies to discover the virtualenv and fail if we can't find one?

**Comment by garnaat** [comment]
I think this is really a question about what the contract is between builder and the Python workflow.  If it is the responsibility of the builder to get the right environment set up and then hand it over to the Python workflow then this is not necessary.  In fact, in that case you really don't even have to pass the ``runtime`` param to the Python workflow because it can just assume everything is right.  Or is it the responsibility of the Python workflow to determine that it's environment is capable of building the correct packages for the specified runtime?

**Comment by sanathkr** [comment]
The contract is that the workflow can assume the right version of Python and PIP are available in the path. Either customers or SAM CLI or the builder above will ensure that this is the case. 

Similar to the capabilities, we could make the workflow expose a list of prerequisite commands that the builder checks before running the workflow - #11

**Comment by sanathkr** [comment]
Closing this because we have reached an agreement that this is not required.
